language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aakashc137/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aakashc137/react-test npm test

after_success:
  - docker build -t aakashc137/multi-client ./client
  - docker build -t aakashc137/multi-nginx ./nginx
  - docker build -t aakashc137/multi-server ./server
  - docker build -t aakashc137/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  docker push aakashc137/multi-client
  docker push aakashc137/multi-nginx
  docker push aakashc137/multi-server
  docker push aakashc137/multi-worker